"""initial_schema

Revision ID: 0001
Revises:
Create Date: 2026-09-25 00:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event', sa.String(length=32), nullable=False),
    sa.Column('from_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('to_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approved_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('detail_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_log_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('eval_labels',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sample_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('labeler', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eval_labels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eval_labels_comment_id'), ['comment_id'], unique=False)

    op.create_table('examples',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags_json', sa.JSON(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_comment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reviewer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fact_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('reviewer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('caption', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('media_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('media_refs_json', sa.JSON(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('brief_json', sa.JSON(), nullable=True),
    sa.Column('brief_version', sa.Integer(), nullable=False),
    sa.Column('context_status', sa.String(length=32), nullable=False),
    sa.Column('sensitivity_flag', sa.Boolean(), nullable=False),
    sa.Column('sensitivity_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('monitored', sa.Boolean(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('checkpoint_cursor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('next_poll_at', sa.DateTime(), nullable=True),
    sa.Column('poll_interval_s', sa.Integer(), nullable=True),
    sa.Column('quiet_cycles', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_posts_context_status'), ['context_status'], unique=False
        )

    op.create_table('settings',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('voice_rules',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('rules_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('comments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('post_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thread_root_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('author_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_own_reply', sa.Boolean(), nullable=False),
    sa.Column('created_at_platform', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('handling_status', sa.String(length=32), nullable=False),
    sa.Column('handled_by_draft_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('audience_replied_after_butter', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_comments_handling_status'), ['handling_status'], unique=False
        )
        batch_op.create_index(batch_op.f('ix_comments_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_post_id'), ['post_id'], unique=False)

    op.create_table('drafts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('draft_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('facts_used_json', sa.JSON(), nullable=True),
    sa.Column('missing_context_json', sa.JSON(), nullable=True),
    sa.Column('review_flags_json', sa.JSON(), nullable=True),
    sa.Column('system_flags_json', sa.JSON(), nullable=True),
    sa.Column('post_brief_version', sa.Integer(), nullable=False),
    sa.Column('voice_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('approved_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approved_text_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approved_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('invalidated_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auto_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drafts_comment_id'), ['comment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drafts_status'), ['status'], unique=False)

    op.create_table('outbound_tasks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('draft_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('approved_text_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('lock_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('returned_reply_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_class', sa.String(length=32), nullable=True),
    sa.Column('error_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reconciliation_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('outbound_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbound_tasks_draft_id'), ['draft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_tasks_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbound_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbound_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_outbound_tasks_draft_id'))

    op.drop_table('outbound_tasks')
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drafts_status'))
        batch_op.drop_index(batch_op.f('ix_drafts_comment_id'))

    op.drop_table('drafts')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_post_id'))
        batch_op.drop_index(batch_op.f('ix_comments_parent_id'))
        batch_op.drop_index(batch_op.f('ix_comments_handling_status'))

    op.drop_table('comments')
    op.drop_table('voice_rules')
    op.drop_table('settings')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_context_status'))

    op.drop_table('posts')
    op.drop_table('knowledge')
    op.drop_table('examples')
    with op.batch_alter_table('eval_labels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eval_labels_comment_id'))

    op.drop_table('eval_labels')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_log_entity')

    op.drop_table('audit_log')
    # ### end Alembic commands ###
